# Generated by Django 4.2 on 2024-07-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="createtime",
            new_name="ctime",
        ),
    ]
