# Generated by Django 4.2 on 2024-07-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_rename_createtime_article_ctime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="count",
        ),
        migrations.AddField(
            model_name="article",
            name="click",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="upload/"),
        ),
    ]
