# Generated by Django 4.2 on 2024-07-28 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("article", "0003_remove_article_count_article_click_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "permissions": (
                    ("article_delete", "Can Delete Article"),
                    ("article_create", "Can Create Article"),
                    ("article_update", "Can Update Article"),
                )
            },
        ),
        migrations.AddField(
            model_name="article",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
