# Generated by Django 4.2 on 2024-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_alter_article_options_article_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="file",
            new_name="file1",
        ),
        migrations.AddField(
            model_name="article",
            name="file2",
            field=models.FileField(blank=True, null=True, upload_to="upload/"),
        ),
        migrations.AddField(
            model_name="article",
            name="file3",
            field=models.FileField(blank=True, null=True, upload_to="upload/"),
        ),
        migrations.AddField(
            model_name="article",
            name="file4",
            field=models.FileField(blank=True, null=True, upload_to="upload/"),
        ),
        migrations.AddField(
            model_name="article",
            name="file5",
            field=models.FileField(blank=True, null=True, upload_to="upload/"),
        ),
    ]
